FROM node:20-alpine AS deps
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend ./
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=4173

COPY --from=deps /app/build ./build
COPY --from=deps /app/package*.json ./
RUN npm install --omit=dev

EXPOSE 4173
CMD ["node", "./build/index.js"]
